### ISSUE TITLE
Spring Security Configuration deprecations

### ISSUE THREAD

**Issue by eidottermihi** [it-at-m/appswitcher-server#70]
Current Spring Security config is using deprecated API, it should be updated to use supported API.

`de.muenchen.oss.appswitcher.security.SecurityConfiguration`

Warning:  /home/runner/work/appswitcher-server/appswitcher-server/src/main/java/de/muenchen/oss/appswitcher/security/SecurityConfiguration.java:[51,25] authorizeHttpRequests() in org.springframework.security.config.annotation.web.builders.HttpSecurity has been deprecated and marked for removal
Warning:  /home/runner/work/appswitcher-server/appswitcher-server/src/main/java/de/muenchen/oss/appswitcher/security/SecurityConfiguration.java:[54,25] and() in org.springframework.security.config.annotation.web.configurers.AuthorizeHttpRequestsConfigurer.AuthorizationManagerRequestMatcherRegistry has been deprecated and marked for removal
Warning:  /home/runner/work/appswitcher-server/appswitcher-server/src/main/java/de/muenchen/oss/appswitcher/security/SecurityConfiguration.java:[54,31] oauth2Login() in org.springframework.security.config.annotation.web.builders.HttpSecurity has been deprecated and marked for removal
Warning:  /home/runner/work/appswitcher-server/appswitcher-server/src/main/java/de/muenchen/oss/appswitcher/security/SecurityConfiguration.java:[63,13] authorizeHttpRequests() in org.springframework.security.config.annotation.web.builders.HttpSecurity has been deprecated and marked for removal

Warning:  /home/runner/work/appswitcher-server/appswitcher-server/src/main/java/de/muenchen/oss/appswitcher/security/SecurityConfiguration.java:[77,13] csrf() in org.springframework.security.config.annotation.web.builders.HttpSecurity has been deprecated and marked for removal
Warning:  /home/runner/work/appswitcher-server/appswitcher-server/src/main/java/de/muenchen/oss/appswitcher/security/SecurityConfiguration.java:[77,30] headers() in org.springframework.security.config.annotation.web.builders.HttpSecurity has been deprecated and marked for removal
Warning:  /home/runner/work/appswitcher-server/appswitcher-server/src/main/java/de/muenchen/oss/appswitcher/security/SecurityConfiguration.java:[77,40] frameOptions() in org.springframework.security.config.annotation.web.configurers.HeadersConfigurer has been deprecated and marked for removal
Warning:  /home/runner/work/appswitcher-server/appswitcher-server/src/main/java/de/muenchen/oss/appswitcher/security/SecurityConfiguration.java:[77,65] and() in org.springframework.security.config.annotation.SecurityConfigurerAdapter has been deprecated and marked for removal
Warning:  /home/runner/work/appswitcher-server/appswitcher-server/src/main/java/de/muenchen/oss/appswitcher/security/SecurityConfiguration.java:[77,71] cors() in org.springframework.security.config.annotation.web.builders.HttpSecurity has been deprecated and marked for removal

**Comment by majun1111** [comment]
Hi @eidottermihi, Please assign this issue to me, I'll work on it.

**Comment by eidottermihi** [comment]
Hi @majun1111 - feel free to create a pull request.

**Comment by majun1111** [comment]
Hi @eidottermihi, I have raised a PR. Please review
